# Generated by Django 4.1.2 on 2022-10-25 01:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('class_code', models.CharField(max_length=50)),
                ('hire_date', models.DateField(default=datetime.date(2022, 10, 24))),
                ('terminated_date', models.DateField(null=True)),
                ('survey_sent', models.DateTimeField(null=True)),
                ('eform_submission', models.DateTimeField(null=True)),
                ('work_auth_recieved', models.DateTimeField(null=True)),
                ('name_change_complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EmplRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('byu_id', models.CharField(max_length=9)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MainApp.gender')),
            ],
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YearInProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MainApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MainApp.season')),
            ],
        ),
        migrations.CreateModel(
            name='PayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 24, 19, 57, 43, 187732))),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.employment')),
            ],
        ),
        migrations.AddField(
            model_name='employment',
            name='empl_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MainApp.emplrecord'),
        ),
        migrations.AddField(
            model_name='employment',
            name='position_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MainApp.positiontype'),
        ),
        migrations.AddField(
            model_name='employment',
            name='semester',
            field=models.ManyToManyField(to='MainApp.semester'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MainApp.person')),
                ('international', models.BooleanField()),
                ('year_in_program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MainApp.yearinprogram')),
            ],
        ),
        migrations.AddField(
            model_name='employment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.student'),
        ),
        migrations.AddField(
            model_name='employment',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.instructor'),
        ),
    ]
