# Generated by Django 4.1.2 on 2022-10-25 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='byu_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pay_grad_tuition',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 20, 2, 4, 642084)),
        ),
    ]
