# Generated by Django 4.1.2 on 2022-10-25 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_employment_notes_person_byu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='eform_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='survey_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='terminated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='work_auth_recieved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 20, 9, 6, 710140)),
        ),
    ]
