# Generated by Django 4.1.2 on 2022-10-25 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_employment_eform_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='class_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payrate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 20, 10, 33, 897655)),
        ),
    ]
