# Generated by Django 4.1.2 on 2022-10-25 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_employment_class_code_alter_payrate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='semester',
            new_name='semesters',
        ),
        migrations.AlterField(
            model_name='payrate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 20, 15, 23, 451977)),
        ),
    ]
