# Generated by Django 4.1.2 on 2022-10-25 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_rename_semester_employment_semesters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrate',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 13, 45, 39, 622821)),
        ),
        migrations.AlterField(
            model_name='employment',
            name='hire_date',
            field=models.DateField(default=datetime.date(2022, 10, 25)),
        ),
        migrations.AlterField(
            model_name='payrate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
