# Generated by Django 4.1.2 on 2022-10-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_employment_hire_date_alter_payrate_input_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='work_auth_recieved',
            new_name='work_auth_received',
        ),
    ]
