# Generated by Django 4.1.2 on 2022-10-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_rename_work_auth_recieved_employment_work_auth_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='name_change_complete',
            field=models.BooleanField(default=False),
        ),
    ]
