# Generated by Django 4.1.2 on 2022-11-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_employment_name_change_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
