# Generated by Django 4.1.2 on 2022-11-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_remove_semester_year_semester_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrate',
            old_name='date',
            new_name='effective_date',
        ),
    ]
